{{- if .Values.config.GROUP_ID }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-processor.fullname" . }}-secret
  labels:
    {{- include "edge-processor.labels" . | nindent 4 }}
type: Opaque
data:
  groupId: {{ .Values.config.GROUP_ID | b64enc | quote }}
  servicePrincipalId: {{ .Values.auth.servicePrincipal.servicePrincipalId | default "" | b64enc | quote }}
  privateKey: {{ .Values.auth.servicePrincipal.privateKey | default "" | b64enc | quote }}
  token: {{ .Values.config.TOKEN | default "" | b64enc | quote }}
{{- end }}

