apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-processor.fullname" . }}-secret
  labels:
    {{- include "edge-processor.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.TOKEN | default "" | b64enc | quote }}
